### PR TITLE
When parsing the stream encoding identifier, expose any thrown IOExceptions.

### LINKED ISSUE #188: MslEncoderFactory catches and hides IOExceptions
While reading and writing MSL messages, it is important not to catch and wrap any IOExceptions. Doing so will result in misleading errors and stack traces that seem to imply a non-I/O exception occurred.

It turns out there is at least one location where an IOException is caught and wrapped into a MslEncoderException, in MslEncoderFactory.createTokenizer().

### PR DESCRIPTION
**Pull request by wmiaw**
Fixes #188.
Do not catch IOExceptions in `MslEncoderFactory.createTokenizer()`.
Explicitly check for end-of-stream when reading, instead of relying upon the format to fail identification.

### CODE REVIEW

File: core/src/main/java/com/netflix/msl/io/MslEncoderFactory.java [hunk 1]
```diff
@@ -151,22 +151,26 @@ static String stringify(final Object value) {
...
      * @return the {@link MslTokenizer}.
-     * @throws MslEncoderException if there is a problem reading the byte
-     *         stream identifier or if the encoder format is not supported.
+     * @throws IOException if there is a problem reading the byte stream
+     *         identifier.
+     * @throws MslEncoderException if the encoder format is not recognized or
+     *         is not supported.
      */
-    public MslTokenizer createTokenizer(final InputStream source) throws MslEncoderException {
+    public MslTokenizer createTokenizer(final InputStream source) throws IOException, MslEncoderException {
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/io/MslEncoderFactory.java]: 👍

File: core/src/main/java/com/netflix/msl/io/MslEncoderFactory.java [hunk 2]
```diff
@@ -151,22 +151,26 @@ static String stringify(final Object value) {
...
+            throw new MslEncoderException("End of stream reached when attempting to read the byte stream identifier.");
         
         // Identify the encoder format.
-        final MslEncoderFormat format;
-        try {
-            bufferedSource.mark(1);
-            final byte id = (byte)bufferedSource.read();
-            format = MslEncoderFormat.getFormat(id);
-            bufferedSource.reset();
-        } catch (final IOException e) {
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/io/MslEncoderFactory.java]: 👍

File: core/src/main/java/com/netflix/msl/msg/MessageInputStream.java [hunk 3]
```diff
@@ -199,7 +200,7 @@ private static ICryptoContext getKeyxCryptoContext(final MslContext ctx, final M
      *         authentication data or a master token, or a token is improperly
      *         bound to another token.
      */
-    public MessageInputStream(final MslContext ctx, final InputStream source, final Set<KeyRequestData> keyRequestData, final Map<String,ICryptoContext> cryptoContexts) throws MslEncodingException, MslEntityAuthException, MslCryptoException, MslUserAuthException, MslMessageException, MslKeyExchangeException, MslMasterTokenException, MslUserIdTokenException, MslMessageException, MslException {
+    public MessageInputStream(final MslContext ctx, final InputStream source, final Set<KeyRequestData> keyRequestData, final Map<String,ICryptoContext> cryptoContexts) throws IOException, MslEncodingException, MslEntityAuthException, MslCryptoException, MslUserAuthException, MslMessageException, MslKeyExchangeException, MslMasterTokenException, MslUserIdTokenException, MslMessageException, MslException {
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/msg/MessageInputStream.java]: 👍

File: core/src/main/java/com/netflix/msl/msg/MessageStreamFactory.java [hunk 4]
```diff
@@ -81,7 +82,7 @@
      *         authentication data or a master token, or a token is improperly
      *         bound to another token.
      */
-    public MessageInputStream createInputStream(final MslContext ctx, final InputStream source, final Set<KeyRequestData> keyRequestData, final Map<String,ICryptoContext> cryptoContexts) throws MslEncodingException, MslEntityAuthException, MslCryptoException, MslUserAuthException, MslMessageException, MslKeyExchangeException, MslMasterTokenException, MslUserIdTokenException, MslMessageException, MslException {
+    public MessageInputStream createInputStream(final MslContext ctx, final InputStream source, final Set<KeyRequestData> keyRequestData, final Map<String,ICryptoContext> cryptoContexts) throws IOException, MslEncodingException, MslEntityAuthException, MslCryptoException, MslUserAuthException, MslMessageException, MslKeyExchangeException, MslMasterTokenException, MslUserIdTokenException, MslMessageException, MslException {
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/msg/MessageStreamFactory.java]: 👍

File: core/src/main/java/com/netflix/msl/msg/MslControl.java [hunk 5]
```diff
@@ -2306,6 +2307,20 @@ public MessageInputStream call() throws MslException, MslErrorResponseException,
...
+                if (cancelled(e)) return null;
+                
+                // Maybe we can send an error response.
+                try {
+                    sendError(ctx, debugCtx, null, null, null, MslError.MSL_COMMS_FAILURE, null, out);
+                } catch (final Throwable rt) {
+                    // If we were cancelled then return null.
+                    if (cancelled(rt)) return null;
+                    
+                    throw new MslErrorResponseException("Error receiving the message header.", rt, e);
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/msg/MslControl.java]: 2 questions:
1) If an IOException occurred, is it a good assumption that network communication can still be possible to send a response?

2) Why does the message say "Error receiving the message header." when this exception was a result of sending a response?

File: core/src/main/java/com/netflix/msl/msg/MslControl.java [hunk 6]
```diff
@@ -1668,7 +1669,7 @@ private SendResult send(final MslContext ctx, final MessageContext msgCtx, final
      * @throws InterruptedException if the thread is interrupted while trying
      *         to delete an old master token the received message is replacing.
      */
-    private MessageInputStream receive(final MslContext ctx, final MessageContext msgCtx, final InputStream in, final MessageHeader request) throws MslEncodingException, MslEntityAuthException, MslCryptoException, MslUserAuthException, MslMessageException, MslKeyExchangeException, MslMasterTokenException, MslException, InterruptedException {
+    private MessageInputStream receive(final MslContext ctx, final MessageContext msgCtx, final InputStream in, final MessageHeader request) throws IOException, MslEncodingException, MslEntityAuthException, MslCryptoException, MslUserAuthException, MslMessageException, MslKeyExchangeException, MslMasterTokenException, MslException, InterruptedException {
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/msg/MslControl.java]: 👍

File: core/src/main/java/com/netflix/msl/msg/MslControl.java (hunk 5 above)
Comment (wmiaw) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: 1. It's a weak assumption. But if I can get a response to the remote entity to provide an error, I want to try. The input and output stream states may not be tightly coupled, depending on the underlying protocols and hardware.
2. The error, as far as the local caller is concerned, is that there was a problem receiving the message header. The use of MslErrorResponseException indicates there was also an error attempting to send an error response (see documentation on MslErrorResponseException class).

File: core/src/main/java/com/netflix/msl/msg/MslControl.java [hunk 7]
```diff
@@ -2306,6 +2307,20 @@ public MessageInputStream call() throws MslException, MslErrorResponseException,
                     throw new MslErrorResponseException("Error receiving the message header.", rt, e);
                 }
                 throw e;
+            } catch (final IOException e) {
+                // If we were cancelled then return null.
+                if (cancelled(e)) return null;
```
Comment (furby999) [inline core/src/main/java/com/netflix/msl/msg/MslControl.java]: How does the caller know that a network error occurred?

Comment (furby999) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: Or do we just not care if the thread was interrupted in some fashion?

Comment (wmiaw) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: Are you asking why it returns null if cancelled? If the caller cancelled, then the IOException doesn't matter, because the operation was cancelled. This cancelled() function is checking if the IOException is a result of cancellation.

File: core/src/main/javascript/msg/MslControl.js [hunk 8]
```diff
@@ -2892,6 +2893,12 @@
                                 mslError = e.error;
                                 userMessage = this._ctrl.messageRegistry.getUserMessage(mslError, null);
                                 toThrow = e;
+                            } else if (e instanceof MslIoException) {
+                                recipient = null;
+                                requestMessageId = null;
+                                mslError = MslError.MSL_COMMS_FAILURE;
```
Comment (furby999) [inline core/src/main/javascript/msg/MslControl.js]: 👍

File: core/src/main/java/com/netflix/msl/msg/MslControl.java (hunk 7 above)
Comment (furby999) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: After looking at the method the thread was interrupted - probably because the app was being shutdown - so the  caller doesn't really care about the exception at that point.

Comment (furby999) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: 👍

File: core/src/main/java/com/netflix/msl/msg/MslControl.java (hunk 5 above)
Comment (furby999) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: Maybe a message like - "Error encountered while attempting to send a response as a result of an error that occurred while receiving the message header." ?

Comment (wmiaw) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: The text you're proposing is covered by the definition of MslErrorResponseException: "Thrown when an exception occurs while attempting to create and send an automatically generated error response."

The documentation on MslErrorResponseException says "The detail message should describe the error that triggered the automatically generated error response."

If we change the detail message to not say that, we would have to redefine MslErrorResponseException.

Why do you feel it is important for the detail message to include text covering the specific exception type (i.e. class) that was thrown? Does that help something somewhere?

Comment (furby999) [reply core/src/main/java/com/netflix/msl/msg/MslControl.java]: I just thought it would be more intuitive to the person who sees the message. Bear in mind that most people haven't read all the documentation and aren't likely to remember all of it even if they do. But it's not that big of a deal, hence I approved the PR. The more important issue was addressing the IOException being thrown properly.
