### PR TITLE
Reject "negative" Base64 characters.

### LINKED ISSUE #148: Base64Secure ArrayIndexOutOfBoundsException
Base64Secure could throw another exception when a character is not a base64 character, which would indicate that the input data is corrupt.

`Caused by: java.lang.ArrayIndexOutOfBoundsException: 65533
	at com.netflix.msl.util.Base64Secure.decode(Base64Secure.java:138)
	at com.netflix.msl.util.Base64.decode(Base64.java:103)
	at com.netflix.msl.tokens.MasterToken.<init>(MasterToken.java:307)
	at com.netflix.msl.msg.Header.parseHeader(Header.java:123)
	at com.netflix.msl.msg.MessageInputStream.<init>(MessageInputStream.java:221)
	at com.netflix.msl.msg.NetflixMessageInputStream.<init>(NetflixMessageInputStream.java:82)
	at com.netflix.msl.msg.NetflixMessageStreamFactory.createInputStream(NetflixMessageStreamFactory.java:94)
	at com.netflix.msl.msg.MslControl.receive(MslControl.java:1645)
	at com.netflix.msl.msg.MslControl.access$400(MslControl.java:188)
	at com.netflix.msl.msg.MslControl$ReceiveService.call(MslControl.java:2214)
	... 62 more`

### PR DESCRIPTION
**Pull request by wmiaw**
Fixes #148. Reject if the high-bit is set for any of the Base64-encoded string's characters.

### CODE REVIEW

File: core/src/main/cpp/util/Base64Secure.cpp [hunk 1]
```diff
@@ -121,8 +121,17 @@ std::shared_ptr<ByteArray> Base64Secure::decode(const std::string& s) {
...
     while (p != s.end()) {
     	const char c = *p++;
+
+    	// Ensure the character is not "negative".
+    	if (c & 0x80) {
+    		invalid = true;
+    		continue;
+    	}
+
+    	// Lookup the character in the decoder map.
```
Comment (padolph) [inline core/src/main/cpp/util/Base64Secure.cpp]: Do you really want to just skip, like we do for whitespace? Shouldn't this be an encoding error? What specifically is wrong with the "negative" char?

Comment (wmiaw) [inline core/src/main/cpp/util/Base64Secure.cpp]: All of the invalid = true cases skip in order to not exit early and leak information about a bad decode (since decoding is often related to crypto). There's no lookup in the map for negative characters or characters > 127. It would be a segfault if not for the bitmask `& 0x7F` but that changes the value if the high bit is set.
