### PR TITLE
Change ThriftyUtf8Reader so it is generous in what it accepts.

### LINKED ISSUE #268: ThriftyUtf8Reader is not well behaved
Using the test file located at [https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt), the `ThriftyUtf8Reader` class throws an exception on what it considers problematic character sequences. However the JRE's built-in StreamDecoder does not, and instead handles problems with the special `?` character and moves on.

While it is unlikely that a valid MSL message would have problematic or illegal UTF-8 character sequences, it's possible that non-ASCII characters would be used. ThriftyUtf8Reader needs to be made better, and to behave as expected of a UTF-8 parsing function (i.e. special `?` characters instead of throwing exceptions).

### PR DESCRIPTION
**Pull request by wmiaw**
Fixes #268. Do not throw an exception on malformed or invalid UTF-8 byte sequences. Instead insert the replacement character.
Also expand the checks for proper byte sequences and support decoding of 5- and 6-byte sequences (with the malformed character).

### CODE REVIEW

File: core/src/main/java/com/netflix/msl/io/ThriftyUtf8Reader.java [hunk 1]
```diff
@@ -32,430 +32,276 @@
  */
 public class ThriftyUtf8Reader extends Reader {
     /** Default byte buffer size (8192). */
-    public static final int DEFAULT_BUFFER_SIZE = 8192;
+    public static final int DEFAULT_BUFFER_SIZE = 16384;
```
Comment (aliddeke) [inline core/src/main/java/com/netflix/msl/io/ThriftyUtf8Reader.java]: Any specific reason for doubling the buffer size?  Is this simply to account for possible malformed characters which could take up more space?

Comment (wmiaw) [reply core/src/main/java/com/netflix/msl/io/ThriftyUtf8Reader.java]: A larger buffer is more efficient. I just picked 16384 as a reasonable balance but it could be even bigger.
